export const testOneApiMockReturn = [];
export const testOneDbMockReturn = [];
//---------------
export const testTwoApiMockReturn = [];
export const testTwoDbMockReturn = [
  {
    id: 2,
    battleTime: "20231124T155049.000Z",
    playerName: "",
    playerTag: "",
    playerDeck: [],
    playerCrowns: 1,
    opponentName: "",
    opponentTag: "",
    opponentDeck: [],
    opponentCrowns: 1,
    clanName: "",
    win: 2,
  },
  {
    id: 1,
    battleTime: "20231124T154835.000Z",
    playerName: "",
    playerTag: "",
    playerDeck: [],
    playerCrowns: 1,
    opponentName: "",
    opponentTag: "",
    opponentDeck: [],
    opponentCrowns: 1,
    clanName: "",
    win: 2,
  },
];
//---------------
export const testThreeApiMockReturn = [
  {
    battleTime: "20231124T155049.000Z",
    playerName: "",
    playerTag: "",
    playerDeck: [],
    playerCrowns: 1,
    opponentName: "",
    opponentTag: "",
    opponentDeck: [],
    opponentCrowns: 1,
    clanName: "",
    win: 2,
  },
  {
    battleTime: "20231124T154835.000Z",
    playerName: "",
    playerTag: "",
    playerDeck: [],
    playerCrowns: 1,
    opponentName: "",
    opponentTag: "",
    opponentDeck: [],
    opponentCrowns: 1,
    clanName: "",
    win: 2,
  },
];
export const testThreeDbMockReturn = [];
//---------------
export const testFourApiMockReturn = [
  {
    battleTime: "20231124T155049.000Z",
    playerName: "",
    playerTag: "",
    playerDeck: [],
    playerCrowns: 1,
    opponentName: "",
    opponentTag: "",
    opponentDeck: [],
    opponentCrowns: 1,
    clanName: "",
    win: 2,
  },
  {
    battleTime: "20231124T154835.000Z",
    playerName: "",
    playerTag: "",
    playerDeck: [],
    playerCrowns: 1,
    opponentName: "",
    opponentTag: "",
    opponentDeck: [],
    opponentCrowns: 1,
    clanName: "",
    win: 2,
  },
];

export const testFourDbMockReturn = [
  {
    id: 1,
    battleTime: "20231124T154835.000Z",
    playerName: "",
    playerTag: "",
    playerDeck: [],
    playerCrowns: 1,
    opponentName: "",
    opponentTag: "",
    opponentDeck: [],
    opponentCrowns: 1,
    clanName: "",
    win: 2,
  },
];
//---------------
export const testFiveApiMockReturn = [
  {
    battleTime: "20231124T155049.000Z",
    playerName: "",
    playerTag: "",
    playerDeck: [],
    playerCrowns: 1,
    opponentName: "",
    opponentTag: "",
    opponentDeck: [],
    opponentCrowns: 1,
    clanName: "",
    win: 2,
  },
  {
    battleTime: "20231124T154835.000Z",
    playerName: "",
    playerTag: "",
    playerDeck: [],
    playerCrowns: 1,
    opponentName: "",
    opponentTag: "",
    opponentDeck: [],
    opponentCrowns: 1,
    clanName: "",
    win: 2,
  },
];

export const testFiveDbMockReturn = [
  {
    id: 2,
    battleTime: "20231124T155049.000Z",
    playerName: "",
    playerTag: "",
    playerDeck: [],
    playerCrowns: 1,
    opponentName: "",
    opponentTag: "",
    opponentDeck: [],
    opponentCrowns: 1,
    clanName: "",
    win: 2,
  },
  {
    id: 1,
    battleTime: "20231124T154835.000Z",
    playerName: "",
    playerTag: "",
    playerDeck: [],
    playerCrowns: 1,
    opponentName: "",
    opponentTag: "",
    opponentDeck: [],
    opponentCrowns: 1,
    clanName: "",
    win: 2,
  },
];
//---------------
export const testSixApiMockReturn = [
  {
    battleTime: "20231124T155049.000Z",
    playerName: "",
    playerTag: "",
    playerDeck: [],
    playerCrowns: 1,
    opponentName: "",
    opponentTag: "",
    opponentDeck: [],
    opponentCrowns: 1,
    clanName: "",
    win: 2,
  },
  {
    battleTime: "20231124T154835.000Z",
    playerName: "",
    playerTag: "",
    playerDeck: [],
    playerCrowns: 1,
    opponentName: "",
    opponentTag: "",
    opponentDeck: [],
    opponentCrowns: 1,
    clanName: "",
    win: 2,
  },
];

export const testSixDbMockReturn = [
  {
    id: 2,
    battleTime: "20231124T130954.000Z",
    playerName: "",
    playerTag: "",
    playerDeck: [],
    playerCrowns: 1,
    opponentName: "",
    opponentTag: "",
    opponentDeck: [],
    opponentCrowns: 1,
    clanName: "",
    win: 2,
  },
  {
    id: 1,
    battleTime: "20231124T130458.000Z",
    playerName: "",
    playerTag: "",
    playerDeck: [],
    playerCrowns: 1,
    opponentName: "",
    opponentTag: "",
    opponentDeck: [],
    opponentCrowns: 1,
    clanName: "",
    win: 2,
  },
];
